### ISSUE TITLE
Fieldset get not hydrated in form

### ISSUE THREAD

**Issue by olekhy** [zfbrasil/doctrine-money-module#16]
My entity:

```php
/**
 * Class Company
 * @package App\Entity
 *
 * @Gedmo\Loggable(logEntryClass="App\Entity\CompanyLogEntry")
 * @Form\Hydrator("DoctrineModule\Stdlib\Hydrator\DoctrineObject")
 * @Form\Type("Account\Form\Company")
 * @Form\Name("company")
 * @ORM\Entity(repositoryClass="App\Repository\Company")
 * @ORM\Table(name="company")
 */
class Company implements CompanyInterface
{

   /**
     * @var Money
     * @Form\Type("money")
     * @Form\Options({"label":"Average value of shopping cart:"})
     * @Form\Name("averageValueOfShoppingCart")
     * @ ORM\Embedded(class = "Money\Money", columnPrefix = "average_value_of_shopping_cart_")
     */
    protected $averageValueOfShoppingCart;

    /**
     * {@inheritdoc}
     */
    public function getAverageValueOfShoppingCart()
    {
        return $this->averageValueOfShoppingCart;
    }

    /**
     * {@inheritdoc}
     */
    public function setAverageValueOfShoppingCart(Money $averageValueOfShoppingCart = null)
    {
        $this->averageValueOfShoppingCart = $averageValueOfShoppingCart;
    }

```
so when form filled and submitted then values stored in db as expected all right!  

here is my form (part)
```html
<div>
     <label for="averageValueOfShoppingCart">Average value of shopping cart:</label>
<div>
<div>
    <select name="averageValueOfShoppingCart[currency]">
    <option selected="selected" value="AED">United Arab Emirates Dirham</option>
    <option value="AFN">Afghan Afghani</option>
    <option value="ALL">Albanian Lek</option>
    <option value="AMD">Armenian Dram</option>
    <option value="ANG">Netherlands Antillean Guilder</option>
</select>
<input type="number" value="111" step="0.01" name="averageValueOfShoppingCart[amount]">            </div>
</div>
```
in db:

```
average_value_of_shopping_cart_amount 11100
average_value_of_shopping_cart_currency AED
```
so when load page now after then no values in form present I get dumped doctrine hydrator and see:

fieldNames for averageValueOfShoppingCart.amount and averageValueOfShoppingCart.currency for this props no method in entity exists and hydration will be skipped. 
I see that money module provides a Fieldset \ZFBrasil\DoctrineMoneyModule\Form\MoneyFieldset with injected his own hydrator 
```php
   $moneyFieldset = new MoneyFieldset();
   $moneyFieldset->setHydrator(new MoneyHydrator());
```
I suppose that this hydrator should fill form elements on $form->bind($companyEntity).
Should or shouldn't? pls tell my that is my mistake ;)

**Comment by fabiocarneiro** [comment]
@olekhy I didn't understand what u mean with this:
> fieldNames for averageValueOfShoppingCart.amount and averageValueOfShoppingCart.currency for this props no method in entity exists and hydration will be skipped.

By what you wrote, I guess the extraction process might not be working for you. There are tests covering that, so I'm not sure this is a problem with the module.

Can you please ```var_dump()``` and  ```die() ``` inside the extract method in  ```MoneyHydrator``` just to make sure it's being called and returning the expected extracted values?

**Comment by olekhy** [comment]
@fabiocarneiro 
>> @olekhy I didn't understand what u mean with this:

>>    fieldNames for averageValueOfShoppingCart.amount and averageValueOfShoppingCart.currency for this props no method in entity exists and hydration will be skipped.

this is from dump  in \DoctrineModule\Stdlib\Hydrator\DoctrineObject::extractByValue  if $object is instance of App\Entity\Company so embedded field @ORM\Embedded(class = "Money\Money" make this. And this leads to skipping extraction by doctrine hydrator.

My dbg changes in MoneyHydrator:

```php
class MoneyHydrator implements HydratorInterface
{
    /**
     * {@inheritDoc}
     */
    public function extract($object)
    {
        var_dump(func_get_args()); die(__METHOD__);
        return [
            'amount' => $object->getAmount(),
            'currency' => $object->getCurrency()->getName()
        ];
    }

    /**
     * {@inheritDoc}
     *
     * @return Money
     */
    public function hydrate(array $data, $object)
    {
        var_dump(func_get_args()); die(__METHOD__);
        return new Money(
            $data['amount'],
            new Currency($data['currency'])
        );
    }
}
```
output at view form is empty so Money Hydrate method wasn't called.
 
log output at form submission on data -> EUR 111
 
```php
Array
        (
            [0] => Money\Money Object
                (
                    [amount:Money\Money:private] => 0
                    [currency:Money\Money:private] => Money\Currency Object
                        (
                            [name:Money\Currency:private] => BRL
                        )

                )

        ),
ZFBrasil\DoctrineMoneyModule\Hydrator\MoneyHydrator::extract
//   ---------------------------
Array
        (
            [0] => Array
                (
                    [currency] => EUR
                    [amount] => 111
                )

            [1] => Money\Money Object
                (
                    [amount:Money\Money:private] => 0
                    [currency:Money\Money:private] => Money\Currency Object
                        (
                            [name:Money\Currency:private] => BRL
                        )

                )

        ),
ZFBrasil\DoctrineMoneyModule\Hydrator\MoneyHydrator::hydrate

```
and 

get not saved yet because  throws an exception now: 
```
Message:

The first parameter of Money must be an integer. It's the amount, expressed in the smallest units of currency (eg cents)

Stack trace:

    #0 /home/o/p/.../vendor/zfbrasil/doctrine-money-module/src/Hydrator/MoneyHydrator.php(42): Money\Money->__construct('111', Object(Money\Currency))

```
maybe annotation in the entity class field is wrong? @Form/ Type ('money') makes me so happy

**Comment by fabiocarneiro** [comment]
@olekhy Make sure ```Filter/AmountFilter``` is being called, the goal with this filter is converting the string input from the form to int. As you can see in your stack trace, its trying to create the ```Money ```instance with a string, so when it persists, it uses the default object provided in the ```MoneyFieldset```, which is BRL 0, and then you get a value 0 when extracting back.

Please enable ```xdebug``` to make sure the type of the amount index in ```ZFBrasil\DoctrineMoneyModule\Hydrator\MoneyHydrator::hydrate``` is integer.

**Comment by olekhy** [comment]
tnx for the hint! BTW I understand why is the filer was defined for!
I'm sure that the input filter spec from money fieldset which was defined in annotation Form\Type() of company entity wasn't attached to form as input filter. no filter and no validators was applied (called) too. this is first trouble I look for solution for.
second trouble is that the form values amount and currency aren't populated from database in form this is main trouble for me and what should I make to achieve that db value extracted into form fields? If you hasn't a idea then I'll close the issue and make my research further on.

**Comment by fabiocarneiro** [comment]
@olekhy Are you sure the money is correctly being persisted? If the value being shown in the form fields are BRL 0, that is the default value for that object in the MoneyFieldset and that probably means the extract is working. Make sure that isn't your database values.

Can you composer show -i and copy the commit id you're using for the module?

**Comment by olekhy** [comment]
so I've find a solution for my first trouble and we has correct supposed that the zend form annotation make this behavior for. 

my short exp:
upon form get build via form annotation Type() and Type is a fieldset, no validators and filters was annotated too. as result we get a fieldset that contains only defaults: filters empty array, validators empty array and required false.

to achieve form input filter get  applied to fieldset elements we should remove default filter from form input filter by fieldset and attach necessary one instead (was defined in method *::getInputFilterSpecification()).

so is my snippet from build a form:
```php
        /* @var Form $form */
        $form = $builder->createForm(EntityApp\Company::class);
        $inputFilter = $form->getInputFilter();
        $inputFilter->remove('billingAddress');
        $inputFilter->remove('sampleAddress');
        $inputFilter->remove('averageValueOfShoppingCart'); // our case

        $form->attachInputFilterDefaults($form->getInputFilter(), $form);

```    
works as expected with only tick invalid by filter named AmountFilter: 

filter should nor filter NOTHING, this make actual '' | null -> 0 and 0 is not empty as integer type so validation for required get lost in this case.    

I've bit changed logic in body of method \ZFBrasil\DoctrineMoneyModule\Filter\AmountFilter::filter($value)

```php
return (null === $value || (is_string($value) && strlen($value) === 0)) ? null : Money::stringToUnits($value);

```
after I've applied this one option required works again and I see the error message!

should/will you fix filter or better a PR me from?   

P.S second trouble is open moreover ;)

**Comment by fabiocarneiro** [comment]
@olekhy if you want to contribute and keep your name here, i'll suggest this snippet:

```php
if (is_string($value) && mb_strlen($value) === 0) {
    return null;
}

return Money::stringToUnits($value);
```

**Comment by olekhy** [comment]
:+1:   i'll make a PR today. 

BTW i tend to using strlen instead of empty because POST/GET/... with 0 is string and could be used for filter as a specific value after filtering by AmountFilter so EUR 0 is valid and not empty instead EUR  '' is empty.  

```php 
var_dump((empty('0') === empty('')) === empty(0)); // true
```
'0' could be filtered to int 0 as expected  
you idea about?

**Comment by fabiocarneiro** [comment]
@olekhy That's right, i didn't considered it. Updated the code above.
