### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Danielss89** [zfbrasil/doctrine-money-module#23]
Are there any docs for this module?
I've added it, and when i update my db i get 
`[Doctrine\ORM\Mapping\MappingException]                                                                          
  No identifier/primary key specified for Entity "Money\Money". Every Entity must have an identifier/primary key. `

**Comment by danizord** [comment]
@Danielss89 Unfortunately we had no time yet to write some docs. But I'll keep this issue open and fix it ASAP.

About your error message, this was because you were using ORM 2.4, correct?

**Comment by Danielss89** [comment]
Super!
Yes, i was using 2.4 ;)

**Comment by netiul** [comment]
Some docs what help a lot indeed :+1:
