### ISSUE TITLE
Doctrine migrations doesn't recognize db changes

### ISSUE THREAD

**Issue by Danielss89** [zfbrasil/doctrine-money-module#28]
Every time i generate a Doctrine Migration with the diff command, the migration contains a change for the currency field of all my money fields:

```sql
ALTER TABLE person_insurance_prices CHANGE price_currency price_currency VARCHAR(255) DEFAULT NULL
```

It does this even though the database is up-to-date with the schema.

**Comment by danizord** [comment]
Hmm, sounds like a doctrine-migrations issue. Any thoughs?

**Comment by Danielss89** [comment]
No not yet, i haven't started debugging, i hoped you might have an answer before i began ;)

**Comment by danizord** [comment]
@fabiocarneiro @gabrielsch anyone encountered this problem?

**Comment by fabiocarneiro** [comment]
I never had to use migrations with this module :(

**Comment by danizord** [comment]
I'm closing because we lack some info to reproduce this case. Tell me if you are still having the issue with lastest version of Doctrine Migrations.
